notifications:
  email: false
  slack:
    rooms:
      secure: E2WCIbmn7S32BRfTODPI8y3p/cyQSmC3M3PFKdJARshoYsuArxuliHa57R4feIderPpbZnAiGv7WLWuL32rSR2nxZnv6KL9syrUhDct/Ak2RTNT8hTY0VeF17tK3fvQ+U2N65InVB6oHucW1PzFTPGKF8GYgarBATGNRuX/MQ0c2wnkXV8VFGTUNu39v1Z0ZcFEVLa2G/avIplPnPQykkxPA3Hoc0o/mBhDq5AStzPoAHQFWfnYzDJE/UGlqTl8j8D2F2iWlB5zDXlb9NoBHR+4YfAEsAyEuXC32ONhdw1KwuQfioZ9Y58fUQ8XC3COVRsvlFpZswzKdcqA9MUsX46mZZGjerQZPth2VNAHD26BxO3rvMFWAy32vlc3q78DVHz5VEteiD5KBWVYec7AU2gU3hE3s89v9YXOcMjPBOfzBwbSiyuz8wNeu+IUUH6mY0nuMEUHUFP9TnbspzDCcVHIqbSwcVsYVh+4YeAFKJ1FJh0TzXPLIHIF5PhjK6XsDvLS/frYKWQyfsKv/R4ciSI0XA4ZfYKaVqu+O2zoZUlWsPxF3TBJyjpCE9JpViMmVpyQ9G8VQLlsZVMuDKmRaHjzoBm6tG3F5yetNH8CD4855VH6PuuHgICsOl/IeZ1v9HtaWyjtok4Rf84yfDKEl0JZRQaUZ/rlIRdjhZ43twTI=
    on_success: always
    on_failure: always 

stages:  
  - name: BUILD
  - name: TEST
  - name: DEPLOY
  - name: ANDROID
  
jobs:
  include:
  - stage: BUILD
    language: node_js
    node_js:
    - '8'
    services:
    - docker
    install: true #skip default installation
    script:
    - bash build.travis.sh
    deploy:
      skip_cleanup: true
      provider: s3
      access_key_id: "$S3_ACCESS_KEY"
      secret_access_key: "$S3_SECRET_ACCESS_KEY"
      bucket: aktnmap-builds
      local_dir: dist
      upload_dir: "$TRAVIS_BUILD_NUMBER/dist"
      on:
        all_branches: true

  - stage: TEST
    language: node_js
    node_js:
    - '8'
    services:
    - docker
    addons:
      code_climate:
        repo_token: 19d3ef0c5e4541c913514b7a3a3825829e5e354f08dc39fd2c03b7898958d597
    install:
    - npm install -g codeclimate-test-reporter
    script:
    - bash test.travis.sh
  
  - stage: DEPLOY
    language: node_js
    node_js:
    - '8'
    services:
    - docker
    install: true #skip default installation
    script:
    - openssl aes-256-cbc -K $encrypted_83630750896a_key -iv $encrypted_83630750896a_iv -in secrets.tar.enc -out secrets.tar -d
    - tar xvf secrets.tar
    deploy:
      provider: script
      skip_cleanup: true
      script: bash deploy.travis.sh
      on:
        all_branches: true
    
  - stage: ANDROID
    language: android
    android:
      components:
      - tools
      - platform-tools
      - tools
      - build-tools-26.0.2
      - android-26
      - extra
    before_install:
    - nvm install 8
    - yes | sdkmanager "platforms;android-26"
    install:
    - pip install --user awscli
    - gem install fastlane
    - yarn install
    script:
    - openssl aes-256-cbc -K $encrypted_83630750896a_key -iv $encrypted_83630750896a_iv -in secrets.tar.enc -out secrets.tar -d
    - tar xvf secrets.tar
    - aws s3 sync s3://aktnmap-builds/$TRAVIS_BUILD_NUMBER/dist cordova/www
    - bash android.travis.sh
    deploy:
      skip_cleanup: true
      provider: s3
      access_key_id: "$S3_ACCESS_KEY"
      secret_access_key: "$S3_SECRET_ACCESS_KEY"
      bucket: aktnmap-builds
      local_dir: cordova/platforms/android/build/outputs/apk
      upload_dir: "$TRAVIS_BUILD_NUMBER/apk"
      on:
        all_branches: true




    


