version: '3'

services:
  testcafe:
    build:
      context: .
      dockerfile: dockerfile.testcafe
    container_name: testcafe
    image: kalisio/testcafe
    links:
      - aktnmap:aktnmap
    depends_on:
      - aktnmap
    environment:
      - GOOGLE_USER
      - GOOGLE_PASSWORD
      - GITHUB_USER
      - GITHUB_PASSWORD
      - NODE_ENV=production
      - APP_URL=172.17.0.1:${PORT}
    volumes:
      - ./test:/opt/testcafe/aktnmap
    command: firefox /opt/testcafe/aktnmap/*.test.js -S -s screenshots
