version: '3'

services:
  aktnmap:
    build:
      context: .
      dockerfile: ./dockerfile.${FLAVOR}
      args:
        BUILD_NUMBER: ${BUILD_NUMBER}
    container_name: aktnmap
    image: kalisio/aktnmap:${VERSION_TAG}
    depends_on:
      - mongodb-aktnmap
    links:
      - mongodb-aktnmap:mongodb
    ports:
      - ${PORT}:8081
    environment:
      - GOOGLE_MAIL_USER
      - GOOGLE_MAIL_PASSWORD
      - GOOGLE_USER
      - GOOGLE_PASSWORD
      - GITHUB_USER
      - GITHUB_PASSWORD
      - APP_SECRET
      - SNS_ACCESS_KEY
      - SNS_SECRET_ACCESS_KEY
      - SNS_ANDROID_ARN
      - S3_ACCESS_KEY
      - S3_SECRET_ACCESS_KEY
      - S3_BUCKET
      - GITHUB_CLIENT_ID
      - GITHUB_CLIENT_SECRET
      - GOOGLE_CLIENT_ID
      - GOOGLE_CLIENT_SECRET
      - BUILD_NUMBER
      - NODE_APP_INSTANCE=${FLAVOR}
      - DB_URL=mongodb://mongodb:27017/aktnmap
    networks:
      - aktnmap
  mongodb-aktnmap:
    container_name: mongodb-aktnmap
    image: mongo
    volumes:
      - mongodb_aktnmap:/data/db
    networks:
      - aktnmap
  mongodb-aktnmap-backup:
    container_name: mongodb-aktnmap-backup
    image: stefanprodan/mgob
    depends_on:
      - mongodb-aktnmap
    links:
      - mongodb-aktnmap:mongodb
    volumes:
      - ./app.backup.yml:/config/aktnmap-${FLAVOR}.yml
    environment:
      - S3_ACCESS_KEY
      - S3_SECRET_ACCESS_KEY
    networks:
      - aktnmap

volumes:
  mongodb_aktnmap:

networks:
  aktnmap:
