version: '3.3'

services:
  app:
    deploy:
      replicas: ${REPLICAS:-1}
      placement:
        constraints:
         - node.role == worker
      labels:
        - "traefik.backend=app"
        - "traefik.docker.network=${DOCKER_NETWORK}"
        - "traefik.enable=true"
        - "traefik.port=${PORT}"
        - "traefik.frontend.entryPoints=http,https"
        - "traefik.frontend.rule=Host:${HOST}.${SUBDOMAIN}"
      restart_policy:
        condition: on-failure
