version: '3.3'

services:
  app:
    environment:
      - DEBUG=${DEBUG}
    deploy:
      replicas: 1
      placement:
        constraints:
         - node.role == worker
      labels:
        - "traefik.backend=app"
        - "traefik.docker.network=${DOCKER_NETWORK}"
        - "traefik.enable=true"
        - "traefik.port=8081"
        - "traefik.frontend.entryPoints=http,https"
        - "traefik.frontend.rule=Host:${HOST}.${SUBDOMAIN}"
      restart_policy:
        condition: on-failure

configs:
  mgob_config:
    file: ./configs/mgob/mgob.yml