version: '3.3'

services:
  app:
    image: kalisio/${APP}:${VERSION_TAG}
    environment:
      - GOOGLE_MAIL_USER=${GOOGLE_MAIL_USER}
      - GOOGLE_MAIL_PASSWORD=${GOOGLE_MAIL_PASSWORD}
      - GOOGLE_USER=${GOOGLE_USER}
      - GOOGLE_PASSWORD=${GOOGLE_PASSWORD}
      - GITHUB_USER=${GITHUB_USER}
      - GITHUB_PASSWORD=${GITHUB_PASSWORD}
      - APP_SECRET=${APP_SECRET}
      - SNS_ACCESS_KEY=${SNS_ACCESS_KEY}
      - SNS_SECRET_ACCESS_KEY=${SNS_SECRET_ACCESS_KEY}
      - SNS_ANDROID_ARN=${SNS_ANDROID_ARN}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}
      - S3_BUCKET=${S3_BUCKET}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - BUILD_NUMBER=${BUILD_NUMBER}
      - NODE_APP_INSTANCE=${FLAVOR}
      - DB_URL=mongodb://mongodb:27017/${APP}
    networks:
      - app-network

volumes:
  mongodb_app:

networks:
  app-network:
    external:
      name: ${DOCKER_NETWORK}
