version: '3.3'

services:
  app:
    environment:
      - DEBUG=
    working_dir: /opt/${APP}
    volumes:
      - ./server-coverage:/opt/${APP}/api/coverage
    command: [ "npm", "run", "test:server" ]
