version: '3.3'

services:
  testcafe:
    build:
      context: ../.
      dockerfile: dockerfile.testcafe
    image: kalisio/testcafe
    depends_on:
      - app
      - mongodb
    environment:
      - GOOGLE_USER
      - GOOGLE_PASSWORD
      - GITHUB_USER
      - GITHUB_PASSWORD
      - NODE_ENV=production
      - DB_URL=mongodb://mongodb:27017/${APP}
      - APP_URL=app:${PORT}
    volumes:
      - ../test:/usr/lib/node_modules/testcafe/${APP}
      - ./client-screenshots:/opt/testcafe/screenshots
    command: firefox ./${APP}/*.test.js -S -s screenshots /opt/testcafe/screenshots --speed 0.9
    networks:
      - app-network

networks:
  app-network:
    external:
      name: ${DOCKER_NETWORK}