version: '3.3'

services:
  testcafe:
    build:
      context: ../.
      dockerfile: dockerfile.testcafe
    image: kalisio/testcafe
    depends_on:
      - app
      - mongodb
    environment:
      - GOOGLE_USER
      - GOOGLE_PASSWORD
      - GITHUB_USER
      - GITHUB_PASSWORD
      - NODE_ENV=production
      - DB_URL=mongodb://mongodb:27017/${APP}
      - APP_URL=${APP}:${PORT}
    volumes:
      - ../test:/opt/testcafe/${APP}
    command: firefox /opt/testcafe/${APP}/*.test.js -S -s screenshots --speed ${TESTCAFE_SPEED:-0.5}
    networks:
      - app-network

networks:
  app-network:
    external:
      name: ${DOCKER_NETWORK}