version: '3.3'

services:
  mongodb:
    image: mongo
    volumes:
      - mongodb_app:/data/db
    networks:
      - app-network

volumes:
  mongodb_app:

networks:
  app-network:
    external:
      name: ${DOCKER_NETWORK}
