version: '3.3'

services:
  mongodb:
    deploy:
      replicas: 1
      placement:
        constraints:
         - node.role == worker
         - node.labels.mongodb == true
      restart_policy:
        condition: on-failure
